# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: KekikAkademi Android Derleyici

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "master"
jobs:
  GithubLog:
    name: "GitHub Etkinliğindeki Her Şeyin LOG'u"
    runs-on: ubuntu-latest
    steps:
      - name: Loglama
        run: |
          echo "${{toJSON(github.event)}}"

  AndroidDerleyici:
    runs-on: ubuntu-latest

    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v2

      - name: Buildozer ile Derle
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      - name: Github Değişkenleri Ayarla
        run: |
          dosya_yolu=${{ steps.buildozer.outputs.filename }}
          dosya_adi=$(basename $dosya_yolu)
          echo dosya_yolu=${dosya_yolu} >> $GITHUB_ENV
          echo dosya_adi=${dosya_adi} >> $GITHUB_ENV
          echo "Dosya Yolu »" ${{ env.dosya_yolu }}
          echo "Dosya Adı  »" ${{ env.dosya_adi }}

      - name: Yapıları Yükle
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.dosya_adi }}
          path: ${{ env.dosya_yolu }}

      - name: Sürüm Oluştur
      
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: ${{ github.event.head_commit.message }}
          files: |
            ${{ env.dosya_yolu }}